### ISSUE TITLE
Imports should be hoisted to the top

### ISSUE THREAD

**Issue by nsaunders** [purescript-contrib/purescript-css#157]
Currently imports are not hoisted to the top of the CSS file. Instead, they are sorted down or remain nested (e.g. within media queries).

However, according to [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/@import#description), _imported rules must precede all other types of rules, except `@charset` rules; as [`@import`] is not a nested statement it cannot be used inside conditional-group at-rules_.

I propose that we follow the example of [sass](#sass) and hoist imports to the top. Perhaps in the future we could also accumulate conditional at-rules in the process since they [_can_ be applied to `@import` statements directly](https://developer.mozilla.org/en-US/docs/Web/CSS/@import#syntax).

#### in
```purescript
query screen (singleton $ maxWidth nil) $
  star & byClass "foo" ? do
    importUrl "https://bomb.com/foo.css"
    color black
```

#### out
```css
@media screen and (max-width: 0) { .foo { color: hsl(0.0, 0.0%, 0.0%) }
@import url(https://bomb.com/foo.css);
 }
```

#### in
```sass
@media screen and (max-width: 0px) {
  .foo {
      @import "https://bomb.com/foo.css";
      color: black;
  }
}
```

#### out
```css
@import "https://bomb.com/foo.css";
@media screen and (max-width: 0px) {
  .foo {
    color: black;
  }
}
```
